### ISSUE TITLE
Wont open.

### ISSUE THREAD

**Issue by MAPReiff** [initPRAGMA/kit-kat#10]
Hello!

Simple issue. When I run the exe, nothing happens. I've tried running as administrator and nothing. Has this issue on two windows 10 PCs.

**Comment by initPRAGMA** [comment]
Install .net framework 4.6.2 and see if thats why?
Also try disconnecting from wifi while you open then when its open, reconnect. (It will give you a message, just hit OK)

**Comment by MAPReiff** [comment]
I have .net framework installed already. Disconnecting from the internet didn't help. I'm going to do whatever windows updates there are, and see if it works.

**Comment by MAPReiff** [comment]
Windows update fixed it, thank you.
