### ISSUE TITLE
Random freezes/disconnects trying to stream to PC

### ISSUE THREAD

**Issue by Fougeta** [initPRAGMA/kit-kat#12]
Apparently the connection with my 3ds is too unstable, sometimes the screen on pc just freezes for 30 seconds ~ 1 minute and return or freezes entirely and requires me to reboot all my 3ds system just for it to work for some more minutes and then freeze again.

I'm trying to stream Pokémon ORAS while sharing screen with a friend of mine on Skype, I don't know if it is a issue with the program or with my connection itself which is not THAT good but acceptable.

I really want to solve this because besides that problem the application is amazing o/

**Comment by initPRAGMA** [comment]
Its the router connnection, theres not really anyway to get it to be better then to hope one day it automatically gets better :l
