### ISSUE TITLE
Unable to open multiple streams at the same time.

### ISSUE THREAD

**Issue by k20stitch** [initPRAGMA/kit-kat#13]
While this may not seem practical for some, i have the bandwidth needed to play.  The issue only arises when i try to connect on another IP address, the first window disappears. I suspect it has something to do with the same ID being used for the view window. Maybe you could ID it dynamically?

Even worse, If i run bootNTR on two devices, and try connecting to one... both streams appear on the screen in alternating frames.

**Comment by initPRAGMA** [comment]
You cant do multiple 3DS's at once.

**Comment by k20stitch** [comment]
Is there any particular reason why? I assume you collect the IP address of the 3DS for more than just verifying that it's connected. If i start NTR on both 3DS and attempt to connect to one, every frame alternates between 3DS. Why is the socket listening for all traffic instead of just the target?
