### ISSUE TITLE
Is it possible to have two viewer instances to capture two 3DS units?

### ISSUE THREAD

**Issue by Loadie** [initPRAGMA/kit-kat#15]
I haven't dug into the source code much... I assume I'd need to modify which ports each 3DS connects with. Is it possible to stream two different units to their own viewer windows?

**Comment by allstevenu** [comment]
It is possible. You will need to use fing (iPhone or android application) so you can find both ips for the 3ds's and 2 windows opened. If this dose not work, Please let me know. It works fine for me so I don't see why it wouldn't work.

**Comment by knyuki90** [comment]
Hi, sorry to hijack the thread but I'm also trying to have two NTR viewer open through kit-kat. What do you mean by having 2 windows opened? I have two instances of kit-kat opened and I have the ip addresses of my 3dses, but whenever I connect, only one NTR viewer opens and the stream overlaps in a flicker.

**Comment by initPRAGMA** [comment]
As far as I know, simply opening 2 seperate kit-kat windows will work, but I havent tested.

**Comment by Loadie** [comment]
@initPRAGMA -- Any update on this? I've tried modifying the ports and stuff via the source code, been programming quite some time, but this didn't work either.

**Comment by SirPsp** [comment]
I would also like to know if this is possible. Simply opening 2 viewers doesn't work. The viewer captures both video feeds at the same time and flicks between the frames.
