### ISSUE TITLE
Create a hotspot

### ISSUE THREAD

**Issue by allstevenu** [initPRAGMA/kit-kat#17]
i am not that smart but i think there should be a option were you can create a hot spot for 3dses to join

this would use your wifi card as a hot spot so people with horible internet(me) could record gameplay with no lag

**Comment by initPRAGMA** [comment]
This was in a old version but was removed as it just causes issues when people use Connectify.me setups.
I recommend you to do the same and just use Connectify.me instead.

**Comment by allstevenu** [comment]
Thank you
I have got my wifi working better by disconnecting my server but it's still nice that you helped me.
