### ISSUE TITLE
Can't connect on BootNTR 3.4 Preview5

### ISSUE THREAD

**Issue by DaliaAsTrue** [initPRAGMA/kit-kat#18]
With latest BootNTR CFW Selector 2.6 Kit-kat can't connect. 
And Kit-Kat show a bug's window. Try it.

**Comment by initPRAGMA** [comment]
get .net framework 4.6.2
if thats not working still, try pressing X+Y and enabling Debugger then trying to connect.

**Comment by DaliaAsTrue** [comment]
Already .net framework 4.6.2 installed, but X+Y Enabling Debugger solved this issue, thank :)

**Comment by initPRAGMA** [comment]
Just a heads up, the updated version of Boot NTR Selector (v2.7.1) fixes this issue, you wont have to Enable Debugger manually.
