### ISSUE TITLE
Update Error!

### ISSUE THREAD

**Issue by lewishack** [initPRAGMA/kit-kat#19]
Been getting this every time I try to use kit-kat.

![screen shot 2017-02-12 at 10 13 59 pm](https://cloud.githubusercontent.com/assets/18566730/22869873/92003dea-f170-11e6-8551-5f708395b220.png)

**Comment by lewishack** [comment]
Also typically I'll get the white screen of death using the NTRviewer window that pops up with the kit-kat GUI, however strangely when I run the standalone NTRViewer exe I get a picture. I don't think it's my Firewall or Antivirus or Windows Defender, since both Firewall and Defender are disabled, and I've never installed Antivirus anyway.

Thanks!

**Comment by initPRAGMA** [comment]
Dont disable them, add them to whitelist, and also get .Net Framework 4.6.2

**Comment by lewishack** [comment]
I whitelisted all ntrviewer.exe inbound and outbound connections , and I already have .Net Framework 4.6.2 installed

**Comment by initPRAGMA** [comment]
Also whitelist kit-kat,
