### ISSUE TITLE
Legand of zelda Ocrina of time help

### ISSUE THREAD

**Issue by allstevenu** [initPRAGMA/kit-kat#20]
i know you arnt cell9(creator of ntr) but i am haveing problems with oot on the 3ds i cant even stream it

**Comment by Committee** [comment]
known issue with oot and 11.3 (which I assume is your current firmware) including but not limited to slowdown and/or laggy cutscenes/gameplay areas.

**Comment by initPRAGMA** [comment]
Yeah its a very weird game, theres nothing we can really do.

**Comment by allstevenu** [comment]
Ok I was just curious because there has been videos of oot on 3ds Ntr
I think there's a mod that enables nfc but that's just a guess
