### ISSUE TITLE
Kit-kat won't launch

### ISSUE THREAD

**Issue by Zyedxy** [initPRAGMA/kit-kat#21]
I'm using Window 7. I have installed framework 4.6.2 but the application just close itself immediately.
I tried to launcher the older versions, the update thing will pop up and i can see kitkat.exe is working in task manager. However, when i try to launch the latest update, it has no respond and nothing pop up.
Furthermore, I have another PC which is also Window 7, that PC can launch kitkat perfectly. I am sure this is my PC problem but I have no clue to fix that. Thaks

**Comment by TiChou** [comment]
I'm same problem on my Windows 7 computer.

When I launch version 1.6.4, the application closes immediately. With version 1.6.3, the application download the latest version.

**Comment by initPRAGMA** [comment]
@Zyedxy Try running as administrator and try downloading Windows 7 Service Pack 1 if its not already installed, if still not working your only option really is to upgrade to windows 8.1 or higher which in my opinion you should have done ages ago.

Windows 7 on the Develepment side is heavilly under used. Think of Windows 7 being like Windows XP at the time when Windows 7 was the most popular.
