### ISSUE TITLE
Crash while trying to push files.

### ISSUE THREAD

**Issue by miltoncandelero** [initPRAGMA/kit-kat#5]
Hey there.

Testing your tool, I pressed "push" before adding files and the app crashed.

(I also had the ftpd server opened on my console instead of the fbi, but it shouldn't crash.)

(It was not the mystical "stoped working", it was a .net unhandled exception).

**Comment by miltoncandelero** [comment]
And you have the same problem that I do. Httolistener uses a system dependence that runs parallel to the app and thus need an special permission through the firewall. :/

I use some CMD shell code to poke a hole and then patch it. The ideal thing would be to design an fileserver that doesn't require httplistener.

I'm working on that, but I have no succedeed so far...

**Comment by initPRAGMA** [comment]
Thanks, I havent messed around with your Boop files much, The current version of Push is v1.0 of Boop. Once you release 1.3 ill probably update push and style up the tab a bit more.

Thanks for the work with Boop and hope you dont mind me putting it in the toolkit.

**Comment by initPRAGMA** [comment]
Fixed in v1.4.2
